@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title System Architecture (C4 Container View)

' --- Contexts ---
Container_Boundary(company, company) {
  Container(gateway, "gateway")
  Container_Boundary(k8s, k8s) {
    Container(user_registry, "user-registry")
    Container(main_app, "main-app")
  }
}

' --- Relationships ---
Rel(gateway, main_app, "https")
Rel(main_app, user_registry, "function-call")
@enduml