@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title System Architecture (C4 Container View)

' --- Contexts ---
ContainerDb_Ext(managed_db, "managed-db")
Container_Boundary(k8s, k8s) {
  ContainerQueue(rabbitmq, "rabbitmq")
  ContainerDb(postgres, "postgres")
  Container(main_app, "main-app")
}

' --- Relationships ---
Rel(main_app, managed_db, "postgres")
Rel(main_app, postgres, "postgres")
Rel(main_app, rabbitmq, "https")
@enduml