' -- Generated with kitab version 0.1.0.0
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title System Architecture (C4 Container View)

' --- Contexts ---
Container_Ext(s3, "s3")
Container_Ext(otel_tracing, "otel-tracing")
Container_Ext(opensearch, "opensearch")
Container_Ext(mailgun, "mailgun")
Container_Ext(host, "host")
Container_Boundary(k8s, k8s) {
  Container(user_registry, "user-registry")
  Container(media_proxy, "media-proxy")
  Container(main_app, "main-app")
  Container_Boundary(media_proxy, media-proxy) {
    Container(pngquant, "pngquant")
  }
}

' --- Relationships ---
Rel(main_app, mailgun, "smtps")
Rel(main_app, media_proxy, "https")
Rel(main_app, otel_tracing, "https")
Rel(main_app, s3, "https")
Rel(main_app, user_registry, "function-call")
Rel(media_proxy, host, "https")
Rel(media_proxy, mailgun, "smtps")
Rel(media_proxy, opensearch, "https")
Rel(media_proxy, otel_tracing, "https")

@enduml