@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title System Architecture (C4 Container View)

' --- Contexts ---
Container(web_app, "web-app")
Container(backend, "backend")

' --- Relationships ---
Rel(web_app, backend, "browser")
@enduml