name: Test

on:
  pull_request:
    paths:
      - "**.hs"
      - "**.cabal"
      - .github/workflows/test.yaml
      - "cabal.project"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tests:
    runs-on:
      - aws-standard-ubuntu24
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - 9.12.2
    steps:

      - uses: actions/checkout@v6

      - name: Cleanup stale ghcup
        run: rm -rf "$HOME/.ghcup"

      - name: Set up Haskell
        id: setup-haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "${{ matrix.ghc }}"
          cabal-version: "latest"

      - name: Install system dependencies
        run: |
           sudo apt install -y libgmp-dev

      - name: Create freeze file
        run: cabal freeze --enable-tests --enable-benchmarks

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-cabal-${{ hashFiles('./dist-newstyle/cache/plan.json') }}
          restore-keys: ${{ runner.os }}-ghc-${{ matrix.ghc }}-

      - name: Build - ${{ matrix.ghc }}
        run: cabal build

      - name: Test - ${{ matrix.ghc }}
        run: cabal test
