name: Formatting

on:
  pull_request:
    paths:
      - "**.hs"
      - .github/workflows/fourmolu.yaml
  push:
    branches:
      - master
    paths:
      - "**.hs"
      - .github/workflows/fourmolu.yaml

jobs:
  fourmolu-formatting:
    runs-on:
      # Use GitHub hosted runner minutes for small jobs.
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-fourmolu@v11
        with:
          version: "0.19.0.1"
