name: Release

on:
  push:
    tags:
      - "v*"

env:
    LANG: "en_GB.UTF-8"
    LANGUAGE: "en_GB.UTF-8"
    LC_ALL: "en_GB.UTF-8"
jobs:
  tests:
    name: "Test on ubuntu-24"
    runs-on:
      - aws-standard-ubuntu24
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - 9.12.2
    steps:

      - name: Set environment
        run: |
            sudo apt update
            sudo apt install -y locales pkg-config
            sudo locale-gen en_GB.UTF-8
            sudo update-locale LANG=en_GB.UTF-8
      - uses: actions/checkout@v6

      - name: Cleanup stale ghcup
        run: rm -rf "$HOME/.ghcup"

      - name: Set up Haskell
        id: setup-haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "${{ matrix.ghc }}"
          cabal-version: "latest"

      - name: Install system dependencies
        run: |
           sudo apt install -y libgmp-dev zlib1g-dev zstd

      - name: Create freeze file
        run: cabal freeze --enable-tests --enable-benchmarks

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ hashFiles('./dist-newstyle/cache/plan.json') }}
          restore-keys: ${{ runner.os }}-ghc-${{ matrix.ghc }}

      - name: Build - ${{ matrix.ghc }}
        run: cabal build

      - name: Test - ${{ matrix.ghc }}
        run: cabal test

  package-macos:
    name: Test on macos-latest
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - 9.12.2
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v6

      - name: Set up Haskell
        id: setup-haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "${{ matrix.ghc }}"
          cabal-version: 'latest'
      - name: Configure
        run: |
          ARCHITECTURE=$(uname -m)
          echo "ARCH=$ARCHITECTURE" >> $GITHUB_ENV
          echo ${{ env.ARCH }}
          cabal configure --enable-tests
      - name: Freeze
        run: cabal freeze --project-file=cabal.release.project
      - name: Cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ hashFiles('./dist-newstyle/cache/plan.json') }}

          restore-keys: ${{ runner.os }}-ghc-${{ matrix.ghc }}

      - name: Build
        run: cabal build --project-file=cabal.release.project

      - name: Test
        run: cabal test --project-file=cabal.release.project all

      - name: Install
        run: |
          mkdir -p distribution/
          cp -f $(cabal --project-file=cabal.release.project list-bin kitab) distribution/

      - name: File type
        run: file distribution/kitab

      - name: Package the kitab executable
        run: |
          KITAB_EXEC=distribution/kitab
          DIR=$(dirname $KITAB_EXEC)
          FILE=$(basename $KITAB_EXEC)
          KITAB_EXEC_TAR=kitab-${{github.ref_name}}-${{ runner.os }}-${{ env.ARCH }}.tar.zst
          tar --zstd -cvf $KITAB_EXEC_TAR -C $DIR $FILE
          echo KITAB_EXEC_TAR=$KITAB_EXEC_TAR >> $GITHUB_ENV

      - name: Upload the kitab executable
        uses: actions/upload-artifact@v6
        with:
          name: kitab-${{github.ref_name}}-${{ runner.os }}-${{ env.ARCH }}
          path: ${{ env.KITAB_EXEC_TAR }}

  package-linux-static:
      name: Test on alpine-3.19
      runs-on: ubuntu-latest
      container: "alpine:3.19"
      strategy:
        fail-fast: false
        matrix:
          ghc:
            - 9.12.2
      steps: 
      - name: Install extra dependencies
        shell: sh
        run: | 
            apk add bash binutils-gold curl \
                curl file g++ gcc git gmp-dev \
                jq libc-dev libffi-dev make \
                musl-dev ncurses-dev perl pkgconfig \
                sudo tar upx xz zlib-dev zlib-static \
                zstd

      - uses: actions/checkout@v6

      - uses: haskell-actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: "${{ matrix.ghc }}"
          cabal-version: 'latest'

      - name: Configure
        run: | 
          ARCHITECTURE=$(uname -m)
          echo "ARCH=$ARCHITECTURE" >> $GITHUB_ENV
          echo ${{ env.ARCH }}
          cabal configure --enable-tests

      - name: Freeze
        run: cabal freeze --project-file=cabal.static.project

      - uses: actions/cache@v5
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ hashFiles('./dist-newstyle/cache/plan.json') }}

          restore-keys: ${{ runner.os }}-ghc-${{ matrix.ghc }}

      - name: Build
        run: cabal build --project-file=cabal.static.project

      - name: Test
        run: cabal test --project-file=cabal.static.project all

      - name: Install
        run: |
          bin=$(cabal -v0 --project-file=cabal.static.project list-bin kitab)
          mkdir distribution
          install ${bin} distribution/kitab

      - name: File type
        run: file distribution/kitab

      - name: Tar kitab executable
        run: |
          KITAB_EXEC=distribution/kitab
          strip $KITAB_EXEC
          upx -9 $KITAB_EXEC
          DIR=$(dirname $KITAB_EXEC)
          FILE=$(basename $KITAB_EXEC)
          KITAB_EXEC_TAR=kitab-${{github.ref_name}}-${{ runner.os }}-static-${{ env.ARCH }}.tar.zst
          tar --zstd -cvf $KITAB_EXEC_TAR -C $DIR $FILE
          echo KITAB_EXEC_TAR=$KITAB_EXEC_TAR >> $GITHUB_ENV

      - name: Upload kitab executable to workflow artifacts
        uses: actions/upload-artifact@v6
        with:
          name: kitab-${{github.ref_name}}-${{ runner.os }}-static-x86_64
          path: ${{ env.KITAB_EXEC_TAR }}
  release:
    name: Create a GitHub release with the binary artifacts
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: ['tests', 'package-linux-static', 'package-macos']

    steps:
    - name: "Download build artifacts"
      uses: actions/download-artifact@v7
      with:
        pattern: kitab-${{github.ref_name}}-*
        merge-multiple: true

    - name: Create GitHub prerelease
      uses: softprops/action-gh-release@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{github.ref_name}}
        draft: true
        files: |
          kitab-${{github.ref_name}}-*
